//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaleLearnCode.GremlinORM {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GremlinORMResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GremlinORMResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TaleLearnCode.GremlinORM.GremlinORMResources", typeof(GremlinORMResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value provided for argument &apos;{argumentName}&apos; must be a valid value of enum type &apos;{enumType}&apos;..
        /// </summary>
        internal static string InvalidEnumValue {
            get {
                return ResourceManager.GetString("InvalidEnumValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {type} does not inherit from {vertexType}. Tracked vertices must inherit from {vertexType}..
        /// </summary>
        internal static string TrackedVertexMustInheritFromVertex {
            get {
                return ResourceManager.GetString("TrackedVertexMustInheritFromVertex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {type} must use the {VertexAttribute} in order to use this type with the Gremlin ORM..
        /// </summary>
        internal static string VertexAttributeMissingException {
            get {
                return ResourceManager.GetString("VertexAttributeMissingException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertex must have an identifier in order to evaluate it within the change tracker; unable to continue..
        /// </summary>
        internal static string VertexMustHaveIdentifierException {
            get {
                return ResourceManager.GetString("VertexMustHaveIdentifierException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {type} does not implement the {VertexAttribute} which is required in order for the vertex to be tracked..
        /// </summary>
        internal static string VertexMustImplementVertexAttributes {
            get {
                return ResourceManager.GetString("VertexMustImplementVertexAttributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertex is not in the change tracker; unable to continue..
        /// </summary>
        internal static string VertexNotInChangeTrackerException {
            get {
                return ResourceManager.GetString("VertexNotInChangeTrackerException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The property &apos;{PropertyName}&apos; is of type &apos;{TypeName}&apos; which is not compatible with Gremlin databases.  Please consider setting the IncludeInGraph flag to false for the property or change the property&apos;s type to a valid type for Gremlin databases..
        /// </summary>
        internal static string VertexPropertyNotValidTypeForGremlin {
            get {
                return ResourceManager.GetString("VertexPropertyNotValidTypeForGremlin", resourceCulture);
            }
        }
    }
}
